[versions]
agp = "8.3.2"
kotlin = "1.9.23"
kotlinJsonSerialization = "1.6.3"
kotlinCoroutineTest = "1.7.3"
coreKtx = "1.13.0"
junit5 = "5.8.2"
lifecycleRuntimeKtx = "2.7.0"
lifecycleRuntimeCompose = "2.7.0"
activityCompose = "1.9.0"
composeBom = "2024.04.01"
composeNavigation = "2.7.7"
material = "1.11.0"
hilt = "2.51.1"
googleServices = "4.4.1"
hiltComposeNavigation = "1.2.0"
firebaseCrashlyticsGradle = "2.9.9"
firebaseBom = "32.8.1"
mockK = "1.13.10"
kotlinComposeCompilerExtension = "1.5.12"
unspecified = "unspecified"

[libraries]
# Kotlin
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-json-serializable = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinJsonSerialization" }
kotlin-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinCoroutineTest" }

# Android
android-tools-build-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# AndroidX
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }

# Hilt
android-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
android-hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltComposeNavigation" }

# Firebase
firebase-crashlytics-gradle = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth-ktx" }

# Junit 5
junit5 = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit5" }
junit5-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit5" }

# Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation" }

# MockK
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockK" }

[plugins]
composeTestApplication = { id = "com.composetest.application", version.ref = "unspecified" }
composeTestLibrary = { id = "com.composetest.library", version.ref = "unspecified" }
composeTestCompose = { id = "com.composetest.compose", version.ref = "unspecified" }
composeTestTest = { id = "com.composetest.test", version.ref = "unspecified" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }
