[versions]
agp = "8.3.1"
kotlin = "1.9.23"
kotlinJsonSerialization = "1.6.3"
coreKtx = "1.12.0"
junit = "4.13.2"
androidJunit = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.7.0"
lifecycleRuntimeCompose = "2.7.0"
activityCompose = "1.8.2"
composeBom = "2024.04.00"
composeNavigation = "2.7.7"
material = "1.11.0"
hilt = "2.51.1"
googleServices = "4.4.1"
hiltComposeNavigation = "1.2.0"
firebaseBom = "32.8.0"
firebaseCrashlyticsGradle = "2.9.9"
kotlinComposeCompilerExtension = "1.5.11"
unspecified = "unspecified"

[libraries]
# Kotlin
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-json-serializable = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinJsonSerialization" }

# Android
android-tools-build-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
android-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
android-hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
android-hilt-test = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }

# AndroidX
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidJunit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltComposeNavigation" }

# Firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-crashlytics-gradle = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }

# Junit
junit = { group = "junit", name = "junit", version.ref = "junit" }

# Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation" }

[plugins]
composeTestApplication = { id = "com.composetest.application", version.ref = "unspecified" }
composeTestLibrary = { id = "com.composetest.library", version.ref = "unspecified" }
composeTestCompose = { id = "com.composetest.compose", version.ref = "unspecified" }
composeTestTest = { id = "com.composetest.test", version.ref = "unspecified" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }
